# Конфигурация для Netlify
[build]
  command = "npm run build"
  publish = "dist"

# Настройки для SPA (Single Page Application)
# Перенаправление всех запросов на index.html для работы React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройки Node.js
[build.environment]
  NODE_VERSION = "22.20.0"
